# finance_chatbot/.streamlit/secrets.toml

GEMINI_API_KEY="AIzaSyBrkHXB0gy1WgoFeUsRusN9xRTXJghNCn4"

# You can add other secrets here if needed, for example:
# MARKET_DATA_API_KEY = "YOUR_MARKET_API_KEY"